### ISSUE TITLE
Error installing under Windows

### ISSUE THREAD

**Issue by andybak** [tdhooper/pollen#1]
> Could not find openssl on your system on this path: openssl

To be honest I'd prefer not to get into debugging this. It tends to confirms a prejudice I have about tangling with node as a way of distributing client side html/css via something as complex as a package manager and build system.

Would it be possible to either:

a) package the built files up in a zip file that I can just either run from the filesystem or via a simple webserver?
b) putting it up on the public internet somewhere so I can just try it out in a browser?

My aim is to just play with it at this stage. I'd be willing to tackle build errors if I was planning to contribute to the project.

**Comment by tdhooper** [comment]
The node server is necessary to allow saving to disk.

I've updated the version on https://tdhooper.github.io/pollen/preview/ where you'll be able to see the editor, but not the gallery.

**Comment by andybak** [comment]
> The node server is necessary to allow saving to disk.

Ah. I didn't know that functionality was there. Makes more sense now. Forgive my js-phobia.

> I've updated the version on <snip>

Thanks! It looks fairly fantastic. I'm happy now.
